# Interaktives Zusatzmaterial: Einführung und Grundlagen der VWL

Willkommen *{{nick}}*!

Vorlesungsskript und Aufgabenblätter für Übungen und Tutorien werden auf der Moodleseite dieses Kurs bereitgestellt. Hier finden Sie nur das interaktive Zusatzmaterial.

{{coursepage_start_clicker(label="Zum Vorlesungsquiz")}}

### Aktuelle interaktive Aufgaben zum Lösen zu Hause

{{coursepage_current_tasks()}}

#< note Anleitung zu den interaktive Aufgaben
Hier werden Sie im Verlauf der Vorlesung verschiedene Aufgaben finden. Zusätzlich zu den Übungen und Tutorien, können Sie mit den Aufgaben Ihren ökonomischen und methodischen Sachverstand sowie Ihre Formulierungsfähigkeiten trainieren.

Jede Aufgabe besteht aus 2 Phasen:

1. Schreibe Lösung: Zunächst hat jeder Studierende ein paar Tage Zeit eine Lösung für die Aufgabe zu schreiben und zu speichern. Solange die Frist noch nicht abgelaufen ist, können Sie Ihre Antwort noch jederzeit überarbeiten. Sie können auf `Preview` klicken um zu sehen, wie Ihre Antwort den anderen Studierenden in der Ratephase angezeigt wird.

2. Rate Musterlösung: Nachdem die Schreibphase abgeschlossen ist, sieht jeder Studierende 4 verschiedene Antworten für die Aufgabe. 3 der 4 Antworten stammen von anderen Studierenden aus der Schreibphase. Eine Antwort ist eine Musterlösung, die wir vorher formuliert haben. Sie müssen nun raten, welche der 4 Antworten die Musterlösung ist. Dabei sortieren Sie durch klicken auf die Antworten, die Antworten in eine Reihenfolge. Je weiter oben Sie die Musterlösung platziert haben, desto mehr Punkte erhalten Sie. (Sie können die Reihenfolge überarbeiten, indem Sie nochmal auf eine bereits markierte Antwort klicken.)

Punkte:
- Punkte für Raten: Wenn Sie die Musterlösung auf Platz 1 platziert haben, erhalten Sie 3 Punkte, auf Platz 2 erhalten Sie 2 Punkte, auf Platz 3 einen Punkt und auf Platz 4 keinen Punkt.
- Punkte für Schreiben: Noch mehr Punkte können Sie erhalten, wenn andere Studierende in der Ratephase ihre geschriebene Antwort auf einen möglichst hohen Platz gesetzt haben. Wenn ein anderer Studierender Ihre Antwort auf Platz 1 gesetzt hat, erhalten Sie **6 Punkte**, auf Platz 2 erhalten Sie 3 Punkte, und auf Platz 3 einen Punkt. Typischerweise werden mehrere Studierende Ihre Antwort platzieren. Sie erhalten den Mittelwert der Punkte aus den Platzierungen dieser Studierenden.

Ihr Ziel in der Schreibphase sollte es also sein, eine Antwort zu formulieren, die für andere Studierende, wie eine Musterlösung aussieht. Da es natürlich erheblich aufwendiger ist, so eine Antwort zu formulieren als die Musterlösung zu raten, können Sie auch deutlich mehr Punkte für das erfolgreiche Schreiben, als für das korrekte Raten erhalten. 
Genauso wie in den Vorlesungsquizzen, sind die Punkte nicht klausurrelevant. Sie erhalten aber eine gewisses Feedback darüber, wie gut es Ihnen gelungen ist eine Musterlösung zu emulieren. Wir vermuten, dass dies eine ganz gute Übung für die Klausur darstellt, wo es eine gute Strategie ist, möglichst nahe an die Musterlösung zu kommen. Wenn Sie dies in Ihren Einstellung aktiviert haben, sehen Sie auf dieser Seite, wie sich ihr relatives Ranking für die interaktiven Aufgaben im Zeitverlauf entwickelt.

Wir freuen uns über Feedback oder Verbesserungsvorschläge zum Design der interaktiven Aufgaben. Schicken Sie einfach eine Email an den Dozenten oder die Übungsleiter.

#>

#< if showRanking

### Entwicklung Ihres Rankings beim Vorlesungsquiz ({{coursepage_num_students()}} Studierende)

{{coursepage_clicker_ranking()}}


#< note 'Hintergrundinfo zum Ranking'

Das Ranking basiert auf den Antworten bei den Quizzen in den Vorlesungen. Die Zahl der Punkte pro richtige Antwort hängt von der Aufgabe ab und von einen Anpassungsfaktor für jeden Vorlesungstermin (siehe weiter unten).

Es gibt keine negativen Punktzahlen. Wenn Sie keine Antwort abgegeben haben, erhalten Sie 0 Punkte. Es macht also stets Sinn, an jedem Quiz teilzunehmen.

Können Sie an einer Vorlesung nicht teilnehmen, haben Sie die Möglichkeit **bevor** die Vorlesung stattfindet, Antworten auf den unten verlinkten interaktiven Slides abzugeben. Sie erhalten aber einen 20% Punktebonus, wenn Sie in der Vorlesung am Quiz teilnehmen.

Das Ranking basiert auf den Gesamtpunkten aus allen bisherigen Vorlesungsterminen. Je mehr Punkte Sie relativ zu Ihren Kommilitonen erzielt haben, desto weiter oben sind Sie im Ranking.

Dieses Ranking und die Punkte aus den Quizzen sind **nicht relevant für die Endnote**. Versuchen Sie also die Quizze zu lösen, ohne vorher die Lösung zu lesen, die manchmal auf den nächsten Slides gegeben ist.

Manchen von Ihnen ist das Ranking vielleicht vollkommen egal. Unsere Vermutung ist aber, dass das Ranking im Schnitt trotzdem die Motivation zur aktiven Teilnahme an der Vorlesung stärken kann. Mit Blick auf Computer- und Videospiele, scheinen Rankings tatsächlich dazu motivieren zu können, viel Zeit mit Aktivitäten zu verbringen, die einem im Ranking weiter nach vorne bringen. 

Die Punkte eines Vorlesungsterminen werden noch durch zwei Faktoren angepasst.

1. Inflation: Wir haben eine positive Inflationsrate bei den Punktzahlen eingebaut. Jeden Vorlesungstermin steigt die Zahl der vergebenen Punkte für eine gleiche Aufgabe um 15%. 
Unsere Motivation für die Inflation ist wie folgt: Ohne Inflation ist es im Verlauf des Semesters tendenziell immer schwieriger das eigene Ranking zu verändern. Für das Ranking werden ja die Punkte aus allen vorangegangen Vorlesungen zusammengezählt, d.h. die im Zeitverlauf wird die aktuelle Vorlesung einen immer kleineren Anteil an der Gesamtpunktzahl haben. Wenn es aber immer schwieriger wird das eigene Ranking zu beeinflussen, sinkt ggf. der motivierende Effekt des Rankings. Eine Punkteinflation wirkt diesem Effekt entgegen, dadurch dass in späteren Vorlesungen ceteris paribus mehr Punkte vergeben werden. 

2. Korrektur für Zahl der Aufgaben in einer Vorlesung: Die Zahl der interaktiven Quiz-Aufgaben kann stärker zwischen Vorlesungsterminen variieren. Wenn n die Zahl der Aufgaben an einem Vorlesungstermin ist, teilen wir die Punkte an diesem Termin durch die Quadratwurzel von n. Z. B. an einem Termin mit 4 Aufgaben teilen wir die Punkte für jede Aufgabe durch 2, an einem Termin mit 9 Aufgaben, würden wir die Punkte für jede Aufgabe durch 3 teilen. Hierdurch wollen wir etwas dem Effekt entgegenwirken, dass manche Vorlesungstermine das Ranking sehr viel stärker beeinflussen können, als andere.

#> end note

#> end if

## Abgeschlossene interaktive Aufgaben

{{coursepage_closed_pq()}}


## Wiederhole Quizze aus der Vorlesung

(Noch nicht implementiert)
{{courser_repeat_clicker_quiz()}}


