# dbCreateSQLiteFromSchema("studentdb.yaml",schema.dir = "D:/libraries/courser/courser/inst/schema", db.name="students.sqlite", db.dir="D:/libraries/courser/courses/vwl/course/db")
# Tables for simple user management
students:
  descr: students table
  table:
    userid: VARCHAR(255)
    hasRegistered: BOOLEAN
    email: VARCHAR(255)
    nick: VARCHAR(255)
    gender: CHARACTER(1)
    subject: VARCHAR(100)
    allowData: BOOLEAN
    allowGrade: BOOLEAN
    token: TEXT
    showRanking: BOOLEAN
    emailRanking: BOOLEAN
    defaultShowRanking: BOOLEAN
  indexes:
    - "CREATE UNIQUE INDEX students1 on students (userid)"

students_hist:
  descr: students table
  table:
    mtime: DATETIME
    userid: VARCHAR(255)
    email: VARCHAR(255)
    nick: VARCHAR(255)
    gender: CHARACTER(1)
    subject: VARCHAR(100)
    allowData: BOOLEAN
    allowGrade: BOOLEAN
    token: TEXT
    showRanking: BOOLEAN
    emailRanking: BOOLEAN
    defaultShowRanking: BOOLEAN
  indexes:
    - "CREATE INDEX students_hist1 on students_hist (userid,mtime)"


studgroups:
  descr: student groups for more interesting rankings
  table:
    groupid: VARCHAR(255)
    userid: VARCHAR(255)
  indexes:
    - "CREATE INDEX studgroups1 on studgroups (groupid)"
    - "CREATE INDEX studgroups2 on studgroups (userid)"

jobs:
  descr: History of runned courser jobs, like updating highscore and sending it
  table:
    time: DATETIME
    jobtype: VARCHAR(255)
  indexes:
    - "CREATE INDEX jobs1 on jobs (jobtype,time)"
    - "CREATE INDEX jobs2 on jobs (time)"
