fields:
  userid:
    label: 'Nutzerkennung'
    readonly: TRUE
#  nick:
#    label: 'Alias'
#    help: |
#      Ihr Alias ist der Name der allen Nutzern angezeigt werden kann.
#      Bitte vermeiden Sie reale Namen, sondern nutzen Sie Namen, die
#      klar als Fantasienamen erkennbar sind. Sie können Ihren Alias
#      auch später noch ändern.
  gender:
    label: 'Geschlecht'
    choices: {'Männlich': m, 'Weiblich': f, 'Unbestimmt': x}
  subject:
    label: 'Studiengang'
    choices:
      - 'Wirtschaftswissenschaften'
      - 'Wirtschaftsmathematik'
      - 'Wirtschafsphysik'
      - 'Wirtschaftschemie'
      - 'Lehramt'
      - 'Anderer Studiengang'
  allowGrade:
    label: 'Anonymisierte Daten dürfen mit Klausurnote verknüpft werden'
    choices: {'Erlauben': TRUE, 'Verbieten': FALSE}
    help: |
      Um den Lernerfolg verschiedener interaktiver Zusatzmodule besser
      einschätzen zu können, würden wir gerne in den anonymisierten Daten
      für Forschungszwecke auch ihre Klausurnote angeben,
      wenn Sie dies erlauben.
